name: Monitor Checker

on:
  schedule:
    - cron: "*/1 * * * *"   # รันทุกๆ 1 นาที
  workflow_dispatch:         # รันเองได้ด้วยปุ่มใน Actions

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run cloud checker
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          ALERT_EMAIL_TO: ${{ secrets.ALERT_EMAIL_TO }}
        run: |
          python - <<'EOF'
          import os
          import json
          import firebase_admin
          from firebase_admin import credentials

          # แปลง JSON string จาก secret เป็น dict
          service_account_info = os.environ['SERVICE_ACCOUNT_JSON']
          service_account_dict = json.loads(service_account_info)

          # สร้าง credential และ initialize Firebase
          cred = credentials.Certificate(service_account_dict)
          firebase_admin.initialize_app(cred)

          # เรียกใช้งานไฟล์ cloud_checker.py
          import checker.cloud_checker as checker
          checker.main()  # สมมติว่าใน cloud_checker.py คุณมีฟังก์ชัน main()
          EOF
